spring:
 datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/CRUD?useUnicode=true&characterEncoding=UTF-8&useSSL=true
     username: root
     password: Yves
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       properties:
         hibernate:
           format_sql: true
       database-platform: org.hibernate.dialect.MySQL5Dialect